In [6]:
import numpy as np
import pandas as pd
import tensorflow as tf


In [7]:
dataset = pd.read_csv(r"C:\Users\soumy\OneDrive\Desktop\ML deployment\deep_learning_model\keras\storepurchasedata_large.csv")


In [8]:
dataset.head()

Age  Salary  Purchased
0   18   20000          0
1   19   22000          0
2   20   24000          0
3   21   28000          0
4   22   60000          1

In [9]:
dataset.describe()

Age        Salary    Purchased
count  1554.000000   1554.000000  1554.000000
mean     44.296010  57042.471042     0.694981
std      17.462458  21209.244800     0.460564
min      18.000000  20000.000000     0.000000
25%      27.000000  46000.000000     0.000000
50%      43.000000  60000.000000     1.000000
75%      62.000000  66000.000000     1.000000
max      69.000000  96000.000000     1.000000

In [10]:

X = dataset.iloc[:, :-1].values
y = dataset.iloc[:,-1].values

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size =.20,random_state=0)

In [12]:

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [14]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Dense(10, activation='relu'),
  tf.keras.layers.Dense(10, activation='relu'),
  tf.keras.layers.Dense(2, activation='softmax')
])

In [15]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [16]:
model.fit(X_train, y_train, epochs=50)


Epoch 1/50
39/39 [==============================] - 1s 3ms/step - loss: 0.6913 - accuracy: 0.6605
Epoch 2/50
39/39 [==============================] - 0s 3ms/step - loss: 0.5657 - accuracy: 0.7409
Epoch 3/50
39/39 [==============================] - 0s 3ms/step - loss: 0.4595 - accuracy: 0.8890
Epoch 4/50
39/39 [==============================] - 0s 3ms/step - loss: 0.3653 - accuracy: 0.9517
Epoch 5/50
39/39 [==============================] - 0s 2ms/step - loss: 0.2823 - accuracy: 0.9590
Epoch 6/50
39/39 [==============================] - 0s 3ms/step - loss: 0.2226 - accuracy: 0.9558
Epoch 7/50
39/39 [==============================] - 0s 2ms/step - loss: 0.1831 - accuracy: 0.9558
Epoch 8/50
39/39 [==============================] - 0s 3ms/step - loss: 0.1594 - accuracy: 0.9558
Epoch 9/50
39/39 [==============================] - 0s 3ms/step - loss: 0.1447 - accuracy: 0.9558
Epoch 10/50
39/39 [==============================] - 0s 3ms/step - loss: 0.1361 - accuracy: 0.9558
Epoch 11/50
39/39 [

In [17]:
loss, accuracy =model.evaluate(X_test, y_test)


10/10 [==============================] - 0s 2ms/step - loss: 0.1072 - accuracy: 0.9550


In [18]:
loss

0.10720830410718918

In [19]:
accuracy

0.9549839496612549

In [20]:
model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 10)                30        
                                                                 
 dense_1 (Dense)             (None, 10)                110       
                                                                 
 dense_2 (Dense)             (None, 2)                 22        
                                                                 
Total params: 162
Trainable params: 162
Non-trainable params: 0
_________________________________________________________________


In [21]:
 prediction1 = model.predict(sc.transform(np.array([[42,50000]])))[:,1]
 prediction1

1/1 [==============================] - 0s 105ms/step


array([0.61663115], dtype=float32)

In [22]:
predict2 = model.predict(sc.transform(np.array([[20,40000]])))[:,1]
predict2

1/1 [==============================] - 0s 30ms/step


array([0.01155521], dtype=float32)

In [23]:
model.save('customer_behavior_model/2')


INFO:tensorflow:Assets written to: customer_behavior_model/2\assets


INFO:tensorflow:Assets written to: customer_behavior_model/2\assets


In [25]:
!ls

 Volume in drive C is Windows
 Volume Serial Number is 8640-FDD4

 Directory of c:\Users\soumy\OneDrive\Desktop\ML deployment\Tensorflow JS\tfjs4

01-08-2023  07:37    <DIR>          .
31-07-2023  21:24    <DIR>          ..
01-08-2023  07:37    <DIR>          customer_behavior_model
31-07-2023  21:24               648 group1-shard1of1.bin
31-07-2023  21:24             2,498 model.json
31-07-2023  21:24            49,494 tf3_keras_age_salary_tfjs.ipynb
31-07-2023  21:24             2,132 tf3_keras_age_salary_tfjs.py
01-08-2023  07:31               762 tfjsdemo.html
               5 File(s)         55,534 bytes
               3 Dir(s)  109,030,436,864 bytes free


In [27]:
!ls customer_behavior_model/2

Invalid switch - "2".


In [14]:
from tensorflow.keras.models import load_model


In [15]:
cust_model = load_model('customer_behavior_model/2/')

In [16]:
 prediction3 = cust_model.predict(sc.transform(np.array([[42,50000]])))[:,1]
 prediction3

1/1 [==============================] - 0s 227ms/step


array([0.61663115], dtype=float32)

In [13]:
predict4 = model.predict(sc.transform(np.array([[20,40000]])))[:,1]
predict4

NameError: name 'model' is not defined

In [32]:
sc.transform(np.array([[20,40000]]))

array([[-1.40863043, -0.81755432]])

In [33]:
sc.transform(np.array([[42,50000]]))

array([[-0.15065689, -0.34524533]])

In [ ]:
!ls

customer_behavior_model  sample_data


In [ ]:
!zip -r customermodel.zip customer_behavior_model  

  adding: customer_behavior_model/ (stored 0%)
  adding: customer_behavior_model/1/ (stored 0%)
  adding: customer_behavior_model/1/assets/ (stored 0%)
  adding: customer_behavior_model/1/variables/ (stored 0%)
  adding: customer_behavior_model/1/variables/variables.data-00000-of-00001 (deflated 55%)
  adding: customer_behavior_model/1/variables/variables.index (deflated 64%)
  adding: customer_behavior_model/1/saved_model.pb (deflated 88%)


In [ ]:
!ls


customer_behavior_model  customermodel.zip  sample_data


In [ ]:
from google.colab import files


In [ ]:
!pip install tensorflowjs

In [2]:
import tensorflowjs as tfjs


In [18]:
tfjs.converters.save_keras_model(cust_model, "/content/")

In [21]:
tfjs.converters.save_keras_model(cust_model,'new_model')

In [19]:
pwd

'c:\\Users\\soumy\\OneDrive\\Desktop\\ML deployment\\Tensorflow JS\\tfjs4'

In [43]:
!ls

customer_behavior_model  group1-shard1of1.bin  sample_data
customermodel.zip	 model.json


In [44]:
!cat model.json

{"format": "layers-model", "generatedBy": "keras v2.4.0", "convertedBy": "TensorFlow.js Converter v2.7.0", "modelTopology": {"keras_version": "2.4.0", "backend": "tensorflow", "model_config": {"class_name": "Sequential", "config": {"name": "sequential", "layers": [{"class_name": "InputLayer", "config": {"batch_input_shape": [null, 2], "dtype": "float32", "sparse": false, "ragged": false, "name": "dense_input"}}, {"class_name": "Dense", "config": {"name": "dense", "trainable": true, "dtype": "float32", "units": 10, "activation": "relu", "use_bias": true, "kernel_initializer": {"class_name": "GlorotUniform", "config": {"seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": null, "bias_regularizer": null, "activity_regularizer": null, "kernel_constraint": null, "bias_constraint": null}}, {"class_name": "Dense", "config": {"name": "dense_1", "trainable": true, "dtype": "float32", "units": 10, "activation": "relu", "use_bias": true, "kernel_initiali

In [45]:
from google.colab import files


In [46]:
files.download('model.json')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [47]:
!ls

customer_behavior_model  group1-shard1of1.bin  sample_data
customermodel.zip	 model.json


In [48]:
files.download('group1-shard1of1.bin')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>